spring:
  datasource:
#    hikari:
#      validation-timeout: '2000'
#      idle-timeout: '600000'
#      maximum-pool-size: '10'
#      auto-commit: 'true'
#      connection-init-sql: SELECT 1
#      connection-timeout: '5000'
#      max-lifetime: '1800000'
#      minimum-idle: '10'
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ssafy
    username: ssafy
    url: jdbc:mysql://1.226.205.3:3306/test?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&allowMultiQueries=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    format_sql: true
    use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  redis:
    host: 127.0.0.1
    port: 6379
file:
  path:
    upload-files: C:/board/upload/fileUpload/
    nodeValue: C:/board/upload/
    upload-images: C:/board/upload/imageUpload

## mac

#file:
#  path:
#    upload-files: /Users/troment/board/upload/fileUpload/
#    nodeValue: /Users/troment/board/upload/
#    upload-images: /Users/troment/board/upload/imageUpload

server:
  port: '80'
logging:
  org:
    springframework:
      security: DEBUG
  level:
    root: info
    com:
      ssafy: debug
jwt:
  secret: coffeeismaximcoffeeismaximcoffeeismaximcoffeeismaxim
  live:
    atk: 300000